export const enum FontJustify {
    JUSTIFYLEFT = "JUSTIFYLEFT",
    JUSTIFYCENTER = "JUSTIFYCENTER",
    JUSTIFYRIGHT = "JUSTIFYRIGHT",
    JUSTIFYTOP = "JUSTIFYTOP",
    JUSTIFYBOTTOM = "JUSTIFYBOTTOM",
}