export const enum FontJustify {
    //Horizontal
    JUSTIFYLEFT = "JUSTIFYLEFT",
    JUSTIFYRIGHT = "JUSTIFYRIGHT",
    JUSTIFYCENTER = "JUSTIFYCENTER",

    //Vertical
    JUSTIFYMIDDLE = "JUSTIFYMIDDLE",
    JUSTIFYTOP = "JUSTIFYTOP",
    JUSTIFYBOTTOM = "JUSTIFYBOTTOM",
}